on: [push]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  two:
    runs-on: ubuntu-latest
    needs: one
    steps:
      - name: print first job output
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        uses: actions/KittyJose/InsightsDev@main
        with:
           json: "$GITHUB_CONTEXT"
